### ISSUE TITLE
Rename and simplify `prepare_constraints`

### ISSUE THREAD

**Issue by upsj** [upsj/terraphast-one#10]
Something like `create_supertree_data` without the `root` parameter, since it can be determined from the bitmatrix

**Comment by amkozlov** [comment]
Just to clarify, now I have to perform 3 steps:

```c++
  auto root_index = find_root(bm);   // find_root is not part of terraphast
  reroot_at_taxon_inplace(tree, root_index);
  supertree = prepare_constraints(tree, bm, root_index);
```

which could all be combined into one simple call 
```c++
  supertree = create_supertree_data(tree, bm);
```
hiding all this complexity from the user.
