### ISSUE TITLE
Dangerous type conversion

### ISSUE THREAD

**Issue by klust** [upsj/terraphast-one#20]
https://github.com/upsj/terraphast-one/blob/6fdd51482a18aebc6edd8f1806fbaf51b929a281/lib/bits.hpp#L14

This line does an implicit type conversion from (on my machine) a 64-bit unsigned integer type to an 8-bit unsigned integer type. I ran across it while compiling RAxML-NG, and since the CMake configuration process selects the option to treat warnings as errors, the Intel C++ compiler (I was using 19.0.4) rightfully stops the compilation (which of course was easily corrected by changing the CMakeLists.txt file, and I can see that the result will always fit a uint8_t so the warning is not that important). The solution could be an explicit type case, eg.g., return (uint8_t) (i % word_bits);

**Comment by upsj** [comment]
This seems to be an issue in the upstream RAxML-NG (or @amkozlov's fork of this repository) which was already fixed in this repository.

**Comment by klust** [comment]
Indeed. I overlooked that the return type has changed compared to the @amkozlov's fork of this repository. I applied the change to my local copy of the RAxML-NG code and it now compiles without problems with Intel also. So the bug report can be closed.
