### ISSUE TITLE
Automatically create comprehensive taxon

### ISSUE THREAD

**Issue by upsj** [upsj/terraphast-one#4]
Count the number of partitions for every taxon, take the taxon with maximum partition count and make it comprehensive.

**Comment by stamatak** [comment]
This is the force option I mentioned in one of my emails, thanks.

**Comment by upsj** [comment]
This is somewhat possible with 42671720e6c4d7c8b6e48fea0f40c37b6fcc82cb, only need to add this option to the C interface now
